// Generated by CoffeeScript 1.6.3
define(['jquery', 'utils/log'], function($, log) {
  log('special/ururu.coffee executed');
  return function() {
    return $('body').append('<div class=\"msg\">Special: ururu!</div>');
  };
});
