// Generated by CoffeeScript 1.6.3
var __slice = [].slice;

define(['jquery', './time-now'], function($, timeNow) {
  var $logDiv, log, logToConsole, pendingItems;
  $logDiv = null;
  pendingItems = [];
  $(document).ready(function() {
    $logDiv = $('.log');
    if ($logDiv && pendingItems.length) {
      $logDiv.append(pendingItems.join('\n'));
    }
  });
  logToConsole = typeof (typeof console !== "undefined" && console !== null ? console.log : void 0) === 'function' ? function() {
    var args;
    args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    return console.log.apply(console, ["" + (Math.round(timeNow())) + " ms:"].concat(args));
  } : function() {};
  return log = function() {
    var args, logMessage;
    args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    logToConsole.apply(null, args);
    logMessage = "" + (Math.round(timeNow())) + " ms: " + (args.join(', ')) + "<br>";
    if ($logDiv) {
      $logDiv.append(logMessage);
    } else {
      pendingItems.push(logMessage);
    }
  };
});
