// Generated by CoffeeScript 1.6.3
define([], function() {
  var timeNow;
  return timeNow = (typeof performance !== "undefined" && performance !== null ? performance.now : void 0) ? function() {
    return performance.now();
  } : function() {
    return null;
  };
});
