
// Generated by CoffeeScript 1.6.3
require(['main'], function() {
  return require(['jquery', 'utils/log', 'backbone'], function($, log) {
    log('page.coffee executed');
    return $('body').append('Page text');
  });
});

define("page", function(){});
