// Generated by CoffeeScript 1.6.3
require(['jquery', 'utils/log', 'settings'], function($, log, settings) {
  log('page.coffee executed');
  return $('body').append("<div class=\"msg\">Dynamic text: " + settings.message + "</div>");
});
