// Generated by CoffeeScript 1.6.3
require(['special/lib'], function() {
  return require(['jquery', 'special/print-ururu', 'utils/log', 'settings'], function($, printUruru, log, settings) {
    log('page-heavy.coffee executed');
    $('body').append("<div class=\"msg\">Dynamic text: " + settings.message + "</div>");
    return printUruru();
  });
});
